services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mosesamwoma}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      POSTGRES_DB: ${POSTGRES_DB:-chesslytics_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-mosesamwoma} -d ${POSTGRES_DB:-chesslytics_db}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      STOCKFISH_PATH: /usr/bin/stockfish
      POSTGRES_USER: ${POSTGRES_USER:-mosesamwoma}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      POSTGRES_DB: ${POSTGRES_DB:-chesslytics_db}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      GROQ_API_KEY: ${GROQ_API_KEY:-}
      GROQ_MODEL: ${GROQ_MODEL:-openai/gpt-oss-120b}
      UPLOAD_DIR: /data/uploads
      ANALYSIS_DIR: /data/analysis
      STOCKFISH_DEPTH: "12"
      CORS_ORIGINS: http://127.0.0.1:5173,http://127.0.0.1:8080
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  postgres-data:
