import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import * as coachService from '../services/coachService.js'

export default function Coach() {
  const [data, setData] = useState(null)
  const [error, setError] = useState(null)
  const [loading, setLoading] = useState(true)
  const [regenerating, setRegenerating] = useState(false)

  const load = useCallback((refresh) => {
    const setBusy = refresh ? setRegenerating : setLoading
    setBusy(true)
    setError(null)
    coachService
      .getInsight({ refresh })
      .then((result) => {
        setData(result)
        setBusy(false)
      })
      .catch((err) => {
        setError(err)
        setBusy(false)
      })
  }, [])

  useEffect(() => {
    load(false)
  }, [load])

  if (error) {
    const missing = error.status === 404
    const noKey = error.status === 503
    return (
      <div className="notice">
        {missing ? (
          <>
            No profile yet. Import a PGN and run an analysis on the{' '}
            <Link to="/games">Games</Link> page first.
          </>
        ) : noKey ? (
          <>Set GROQ_API_KEY on the backend to enable AI coaching commentary.</>
        ) : (
          <>
            {error.message}{' '}
            <button type="button" className="button" onClick={() => load(false)}>
              Retry
            </button>
          </>
        )}
      </div>
    )
  }

  if (!data) {
    return <p className="muted">{loading ? 'Generating your coaching notes…' : 'No insight yet.'}</p>
  }

  return (
    <div className={loading ? 'loading-dim' : undefined}>
      <div className="page-head">
        <div>
          <h1>Coach</h1>
          <p className="subtitle">
            {data.player ? `${data.player} · ` : ''}AI commentary grounded in your mined
            patterns, generated by {data.model}
          </p>
        </div>
        <button
          type="button"
          className="button"
          onClick={() => load(true)}
          disabled={regenerating}
        >
          {regenerating ? 'Regenerating…' : 'Regenerate'}
        </button>
      </div>

      <div className="card">
        <h2>The big picture</h2>
        <p>{data.summary}</p>
      </div>

      <div className="card" style={{ marginTop: 16 }}>
        <h2>This week's drill</h2>
        <p>{data.focus_drill}</p>
      </div>

      <div className="grid grid-two" style={{ marginTop: 16 }}>
        {(data.sections || []).map((section) => (
          <div className="card" key={section.title}>
            <h2>{section.title}</h2>
            <p>{section.body}</p>
          </div>
        ))}
      </div>
    </div>
  )
}
